### ISSUE TITLE
Optional requirements

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasgen#16]
I was thinking we should make some of the requirements optional. Mostly because the allensdk has some annoying dependencies, but also because as more atlases are added, we may need more packages to read data formats etc.

@vigji, @FedeClaudi  what do you think about either:
* `pip install .[allensdk]` to only install certain packages when needed
* `pip install .[allenmouse]`, `pip install .[azba]` etc to only install packages needed for specific atlases when needed

**Comment by FedeClaudi** [comment]
I like the latter best, and yeah allensdk is a pain to install so I agree!

**Comment by adamltyson** [comment]
At the moment, are there any other packages that are only required by a subset of atlases? I can add the `[allenmouse]` which would be needed for the allen, kim and osten atlases. 

Side note, we should also document this, or at least list the atlases that require each extra in the setup file.

**Comment by FedeClaudi** [comment]
AFAIK it's only the allenmouse

**Comment by vigji** [comment]
I agree with the latter! Yes, we should clean up a bit the code for consistency in all scripts and write this in the doc. I just wonder, I dson't like the idea of everyone writing up stuff in the setup.py, maybe we can have a folder where everyone writes specific requirements in text files and then we parse them out
Also, a .[all] for having everything

**Comment by adamltyson** [comment]
I don't really have a preference either way. We'd review any changes to the setup file anyway. if anything, I'd probably rather it was all just done in setup.cfg.

Do we want an .[all]? The current behaviour is already broken as the numpy version required by allensdk is already too old for some other packages. This issue is about dealing with potentially many incompatible dependencies as atlas numbers increase. 

Happy to go with consensus.

**Comment by FedeClaudi** [comment]
Chances are few people would need a `.[all]` options other than core developers? And we can just manually install each extra requirements. Agreed probably having it all in setup.py ensures that we can more easily monitor it.

**Comment by vigji** [comment]
the all was just for us, but sure, we can manage the extra, and it also does not really make sense unless the requirements are split in text files, an [all] in the setup would just be duplicated code!
If @FedeClaudi votes for changes in the setup I will go with the majority :)

**Comment by adamltyson** [comment]
Up to you guys. If the PR is approved by both of you, I'll merge. Otherwise, happy to edit it.

**Comment by vigji** [comment]
I think @FedeClaudi made his point, so, happy to go with current edit of setup!

**Comment by adamltyson** [comment]
Great, merged.
