### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasgen#21]
I'm using this package as a dependency, so it would be useful to be able to install with `pip install bg-atlasgen`.

**Comment by vigji** [comment]
What are you using it in?

**Comment by adamltyson** [comment]
> What are you using it for?

A pipeline (private for now) to create an atlas from scratch, i.e. from raw data to packaged atlas, not just from existing atlas files. It would be useful to move `atlas_scripts` to another top level dir, and release the utilities as a stand-alone package on PyPI.

**Comment by willGraham01** [comment]
Going to close this as it has now been resolved with the release of `brainglobe-atlasapi` :partying_face: https://github.com/brainglobe/brainglobe-atlasapi
