### ISSUE TITLE
Add tooling to automatically check that atlases are packaged correctly. 

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasgen#33]

**Comment by JoeZiminski** [comment]
This is a nice idea, some things that could be done off the top of my head:

1) calculate total overlap between reference image and annotation (would expect this to be say >99% overlap)
2) could look for meshes of the tested atlas that have duplicates in other atlases (e.g. allen_mouse_10um). Check that there is at least some overlap between these meshes

+ other checks to ensure all expected files are there, all names are consistent, the atlas will download from GIN

**Comment by adamltyson** [comment]
Closing as duplicate of #13
