### ISSUE TITLE
mesh_utils ImportError

### ISSUE THREAD

**Issue by kailynkfields** [brainglobe/bg-atlasgen#6]
While trying to do the following:
`from bg_atlasgen.mesh_utils import create_region_mesh, Region`
I get an error from
`from vedo.applications import Browser, Slicer`
`ImportError: cannot import name 'Slicer' from 'vedo.applications`

Looking through https://github.com/marcomusy/vedo/blob/master/vedo/applications.py I see a SlicerPlotter and Slicer2d function and based on the arguments passed into Slicer in create_region_mesh it looks like Slicer may have been renamed to SlicerPlotter?

**Comment by FedeClaudi** [comment]
Yeah that's very likely.
We'll need to fix this, but as a quick workaround you can try installing an older version of vedo.

**Comment by kailynkfields** [comment]
On my device I altered the import line to 
`from vedo.applications import Browser`
`from vedo.applications import SlicerPlotter as Slicer`
That seemed to work

**Comment by adamltyson** [comment]
This is now fixed in #7
