### ISSUE TITLE
whs_sd_rat_39um atlas axes are mixed up

### ISSUE THREAD

**Issue by LSeu-994** [brainglobe/bg-atlasgen#60]
Few days ago i raise an issue on Brainrender repos about a issue with using the slice command and the camera positioning :
https://github.com/brainglobe/brainrender/issues/204#issuecomment-1100002950

The axes from this Atlas seems to be miss oriented causing trouble with the manipulation of the root Atlas.
![Capture](https://user-images.githubusercontent.com/95351758/163970092-8095ea2e-3bb4-4eb6-ae88-d5f18a99e3cb.JPG)

Any idea on who import this atlas and how we can colaborate to resolve this issue.

Thx

**Comment by alessandrofelder** [comment]
Closed by [new version (1.1) of rat atlas.](https://gin.g-node.org/BrainGlobe/atlases/src/master/whs_sd_rat_39um_v1.1.tar.gz)
