### ISSUE TITLE
Rename to `brainglobe-atlasgen`

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasgen#87]
The names of tools are inconsistent, and `bg` isn't very informative. We agreed in the [last dev meeting](https://github.com/brainglobe/BrainGlobe/discussions/350) to move to `brainglobe-xyz` as a standard.

**Comment by adamltyson** [comment]
But also see https://github.com/brainglobe/BrainGlobe/issues/43

**Comment by willGraham01** [comment]
Going to close this in favour of https://github.com/brainglobe/BrainGlobe/issues/43 - one of the tasks will make this a non-issue anyway.
